FROM jupyter/datascience-notebook

# Physics15b requested Julia and the jupyter/datascience-notebook
# comes with that already, so we're just deriving from that base image.
#
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
#
# If the course requires any additional packages not already included,
# install them here.

